[[https://travis-ci.com/org-pivotal/org-pivotal][https://travis-ci.com/org-pivotal/org-pivotal.svg?branch=master]]
[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg]]
[[http://hits.dwyl.io/org-pivotal/org-pivotal][http://hits.dwyl.io/org-pivotal/org-pivotal.svg]]
[[https://coveralls.io/github/org-pivotal/org-pivotal?branch=master][https://coveralls.io/repos/github/org-pivotal/org-pivotal/badge.svg?branch=master]]
[[https://github.com/org-pivotal/org-pivotal/graphs/commit-activity][https://img.shields.io/badge/Maintained%3F-yes-green.svg]]

# org-pivotal
** Summary
   :PROPERTIES:
   :CUSTOM_ID: summary
   :END:

org-pivotal is a utility to extend org-mode with Pivotal Tracker abilities

** Installing
   :PROPERTIES:
   :CUSTOM_ID: installing
   :END:

You will need Emacs 26.1+, =make= and [[https://github.com/cask/cask][Cask]] to build the project.

#+BEGIN_SRC sh
    cd org-pivotal
    make && make install
#+END_SRC

** Initial setup
   :PROPERTIES:
   :CUSTOM_ID: initial-setup
   :END:
Before using the tracker you must setup your pivotal API key in Emacs. You can obtain the key from the [[https://www.pivotaltracker.com/profile][Profile]] link in the Pivotal Tracker web application.

After obtaining the ky, you have to manually add it to your .emacs.d or .spacemacs like this:

#+BEGIN_SRC emacs-lisp
  (setq org-pivotal-api-token "your-secret-token")
#+END_SRC

If you don't want to set it directly in your Emacs's .el file, you can export it to shell environment and use =getenv= to read it from within Emacs

#+BEGIN_SRC emacs-lisp
  (setq org-pivotal-api-token (getenv "PIVOTAL_API_TOKEN"))
#+END_SRC

** Usage
   :PROPERTIES:
   :CUSTOM_ID: usage
   :END:

1. To connect your org buffer to an existing project:

   #+BEGIN_SRC
   M-x org-pivotal-install-project-metadata
   #+END_SRC
   
   Beware that this will only install properties needed to speak with Pivotal project (and nothing else).
   
2. To pull stories to the org buffer:

   #+BEGIN_SRC
   M-x org-pivotal-pull-stories
   #+END_SRC
   
3. To sync a story to Pivotal, go over that story and execute:

   #+BEGIN_SRC
   M-x org-pivotal-push-story
   #+END_SRC
   
*** Hint

If you are using Spacemacs, you can map all the commands above to leader key for quick access

#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key-for-mode 'org-mode "pi" 'org-pivotal-install-project-metadata)
  (evil-leader/set-key-for-mode 'org-mode "pp" 'org-pivotal-pull-stories)
  (evil-leader/set-key-for-mode 'org-mode "pu" 'org-pivotal-push-story)
#+END_SRC

** Contributing
   :PROPERTIES:
   :CUSTOM_ID: contributing
   :END:

Yes, please do! See [[./CONTRIBUTING.md][CONTRIBUTING]] for guidelines.

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:

See [[./COPYING][COPYING]]. Copyright (c) 2018 Huy Duong.
